### ISSUE TITLE
Emit output that is styled like a normal markdown paragraph rather than a CodeBlock

### ISSUE THREAD

**Issue by michaelnt** [pystitch/stitch#27]
I'd like to template some text but it is styles as a code block.

```{python}
import math
print ("The value of pi is {pi:1.3f}".format(pi=math.pi))
```
The following works when outputting to html but gets ignored when outputting to latex.

```{python}
from IPython import display
import math
t = "The value of pi is {pi:1.3f}".format(pi=math.pi)
display.HTML(t)
```

How can I get this to display in both html and latex?

**Comment by TomAugspurger** [comment]
Print messages go through stdout. At the moment, I just [wrap those](https://github.com/pystitch/stitch/blob/master/stitch/stitch.py#L583) in a CodeBlock, mainly to signify that the text is output from a code chunk.

> How can I get this to display in both html and latex?

I thought that `display.display(t)` would work. The documentation says

> By default all representations will be computed and sent to the frontends.
Frontends can decide which representation is used and how.

However, I only see `text/plain` coming through. If that returns representations for `text/html` and `text/pdf` I think we would correct intercept and render it.

**Comment by michaelnt** [comment]
I thought display.Markdown(t) might be a solution that could then be rendered to latex or html by pandoc

**Comment by michaelnt** [comment]
Thanks, that worked for me (for html and latex).

**Comment by TomAugspurger** [comment]
Thinking about it more, when `display.display` says it computes all the representations, that probably means `_repr_latex_`, `_repr_html_`, etc. But strings don't define any of those methods, just `str`.

I'll write a couple tests and merge that tonight. Thanks for trying it out.
