### ISSUE TITLE
Output to reveal.js

### ISSUE THREAD

**Issue by gglanzani** [pystitch/stitch#40]
[First of all, congrats on the release]

Would it be possible, like `nbconvert --to slides`, to output slides in reveal.js format?

I know it would add a lot of complexity to define slides boundaries, but still... 

On of the biggest advantages of Stitch, is that it plays nice with DVSC. With slides, it would become an awesome environment to collaborate on presentations and courses.

**Comment by TomAugspurger** [comment]
It kind of works now, if you take the template from https://gist.github.com/paultopia/0c57899407aed81f6932 and use

```bash
stitch slides.md -o slides.html -t html5 --template=revealjs.html --standalone --section-divs --variable theme="beige"


```

You'd need to disable syntax highlighting, since reveal handles that, which isn't an option yet.

**Comment by TomAugspurger** [comment]
Oh cool, pandoc has a `--no-hightlight` option, so 

```bash
stitch slides.md -o slides.html -t html5 \
    --template=revealjs.html --standalone \
    --section-divs --variable theme="beige"
```

should work, assuming you're in the root of `reveal.js` git repo so that the links in the template work out. Do you have a somewhat complex example to try it out on?

**Comment by gglanzani** [comment]
Hi Tom,

Very cool. Yes, I do have an example, I will try it out today.

When is a new slide inserted btw?

**Comment by gglanzani** [comment]
Sorry, I see that |n is the new slide command

**Comment by TomAugspurger** [comment]
There's also the `--slide-level=n` option, so you can configure that.

I'm  going to close this for now, but let me know if you hit any issues.

**Comment by TomAugspurger** [comment]
Actually, going to reopen this as a reminder to document this, as I think it'll be pretty common.

**Comment by TomAugspurger** [comment]
Closed by https://github.com/pystitch/pystitch.github.io/commit/70bd0010e94f8a3122162d1b07f9d5fc1fa752f8

https://pystitch.github.io/faq.html, https://pystitch.github.io/_downloads/ex_revealjs.txt, and https://pystitch.github.io/_downloads/ex_revealjs.html#/
