### ISSUE TITLE
Link broken in docs and page width

### ISSUE THREAD

**Issue by damienrj** [pystitch/stitch#57]
Hello,
I was looking at the docs some more, and it turns out the link for pypandoc is broken. https://github.com/coldfix/pypandoc.

Also, I was wondering if there was a way to control the page width and boarder when converting to html.
Thanks

**Comment by TomAugspurger** [comment]
Thanks for the pointer, I'll fix that tonight (should be https://github.com/bebraw/pypandoc)

For controlling the page styling, you'll want to pass the `--css=<path/to/file.css>`  The default is at https://github.com/pystitch/stitch/blob/master/stitch/static/default.css if you want to use that as a starting place.

**Comment by damienrj** [comment]
Thanks, I will play with passing a css file.
