### ISSUE TITLE
Cache chunk outputs

### ISSUE THREAD

**Issue by kiwi0fruit** [pystitch/stitch#68]
With caching outputs it would be possible to use Stitch with live preview window like in [Markdown Preview Plus](https://github.com/atom-community/markdown-preview-plus).

It may be straight forward: dump output list of blocks to JSON files in subfolder in the same folder (together with hashes of chunk code or code itself). Then before loading Jupyter kernel check the cache. If mismatch then to reload and re-evaluate all chunks - so that checking should be independent from main evaluation loop.
 
Also to add `--clear-cache` CLI option that forses re-evaluating for cases when only external to document code changed. Or for some logic patterns in wrapper GUI.
Also to add `--no-cache` CLI option that forses re-evaluating but Stitch does not write cache.

TODO: do not forget about fallback chunk options when checking cache changes.

**Comment by grst** [comment]
It gets more complicated if code blocks have variable dependencies. You have to resolve those first, as potentially a small change in one block can invalidate a lot of others. 

Moreover, to re-compute a block further down will require objects of a block further up, which are not available any more. 
In RMarkdown/knitr this is resolved by saving all variables (in our case: `pickleing`) of each code block to the cache directory.

**Comment by kiwi0fruit** [comment]
Nope. It's plain simple. Stitch launches new Jupyter Everytime it runs. It takes lots of time. All I suggest is to check code changes in code blocks (oh! Chunk options should be checked too). If there's any (in first spec version I thought to re-evaluate only following chunks) changes (no matter what they are) - then to re-evaluate the whole document.

This mode is useful for Markdown editing. Chunks editing should be made via Atom/Hydrogen.

**Comment by kiwi0fruit** [comment]
In case of heavy computations performed I plan to use "feather helper" that is a UI wrapper for wesm/feather that simply caches numpy arrays and pandas dataframes. I don't like the idea of rewriting Stitch / using other tool that keeps Jupyter running in the background or caches python objects.

Feather helper interface sample:
https://github.com/kiwi0fruit/pandoctools/blob/master/pandoctools/feather

`# raise Exception` is a comment switch for re-evaluation.

**Comment by kiwi0fruit** [comment]
Yep, my suggestion is not that convenient as `pickleing`. But it's so much easier to implement :-) And it looks like it would be **me** to implement this (as **I** want to use Jupyter+Pandoc+Hydrogen combo together with Atom Markdown Preview Plus live preview).

**Comment by grst** [comment]
@kiwi0fruit, I think your suggestion is a fair start and will work well as long as you only change markdown and no code blocks. 

Still, please keep in mind that pystitch should serve a broader use-case than your specific development setup. 

Cheers, 
Gregor

**Comment by kiwi0fruit** [comment]
Actually I'm not interested in broad use-cases. I have plans for Stitch only for Atom GUI package that has pandoc involving pipelines profile manager (shell scripts with pipelines as switchable configs). And that pipelines have Stitch in it via Knitty wrapper [like this](https://github.com/kiwi0fruit/knitty#usage).

But I will not break Stitch :-) And I'm going to PR all changes that are on metadata/Pandoc AST filter side (other changes go to Knitty).

**Comment by kiwi0fruit** [comment]
BTW: There's no notable Jupyter kernel + Markdown alternatives to Atom/Hydrogen (except [vscodeJupyter](https://github.com/DonJayamanne/vscodeJupyter) may be, but I'm not sure that it's good). Even [Pweave recommends it](http://mpastell.com/pweave/editors.html).

**Comment by kiwi0fruit** [comment]
More details about this simple caching:

There is `is_executable(block, kernel_name, attrs)` check in `stitch.py`. Cache check can be added there and if it fails it: sitch clears cache (or marks as cleared in the folder) and exits with error from `try` area. Checking if cache is cleared is part of the `is_executable(block, kernel_name, attrs)` check and cleared cache cannot trigger stitch exit with error again. And we actually haven't started any Jupyter kernels so we can easily start loop again.

**Comment by kiwi0fruit** [comment]
TODO: do not forget about fallback chunk options when checking cache
changes.

18 янв. 2018 г. 16:02 пользователь "Gregor Sturm" <notifications@github.com>
написал:
